### PR TITLE
Ruby 3.2.2

### PR DESCRIPTION
**Pull request by lavaturtle**
:canned_food:

### CODE REVIEW

**Comment by lavaturtle** [comment]
There seems to be some issue trying to build with ruby 3.2. I tried it locally and got `undefined method 'exists?' for File:Class` deep in some dependency; I think it's related to how we pull webhook data?

**Review by anero — APPROVED** [review]
:+1:

**Comment by lavaturtle** [comment]
I'm going to close this; we can wait to upgrade this repo to ruby 3.2 until [upstream](https://github.com/slatedocs/slate) supports it. (Their github config only goes up to 3.1 right now.)
